/*
 * Copyright (C) 2021 XieChaoJun
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterFourJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterFourJni
#define _Included_com_crab_test_apuedemo_jni_ChapterFourJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterFourJni
 * Method:    fileType
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFourJni_fileType
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFourJni_access
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFourJni_umask
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFourJni_fileLength
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFourJni_truncate
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFourJni_readDir
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
