/*
 * Copyright (C) 2021 XieChaoJun
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterThreeJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterThreeJni
#define _Included_com_crab_test_apuedemo_jni_ChapterThreeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterThreeJni
 * Method:    createHoleFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterThreeJni_createHoleFile
        (JNIEnv *, jclass);

/*
 * Class:     com_crab_test_apuedemo_jni_ChapterThreeJni
 * Method:    ioEfficiency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterThreeJni_ioEfficiency
        (JNIEnv *, jclass, jint);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterThreeJni_fcntl
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterThreeJni_ioctl
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
