/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterFiveJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterFiveJni
#define _Included_com_crab_test_apuedemo_jni_ChapterFiveJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterFiveJni
 * Method:    ioEffective
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFiveJni_ioEffective
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFiveJni_fopen
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterFiveJni_fread
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
