/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterTwelveJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterTwelveJni
#define _Included_com_crab_test_apuedemo_jni_ChapterTwelveJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterTwelveJni
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterTwelveJni_pthreadAttr
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterTwelveJni_mutexAttr
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
