/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterTenJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterTenJni
#define _Included_com_crab_test_apuedemo_jni_ChapterTenJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterTenJni
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterTenJni_signal
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterTenJni_kill
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterTenJni_alarm
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
