/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterSixJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterSixJni
#define _Included_com_crab_test_apuedemo_jni_ChapterSixJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterSixJni
 * Method:    getpwnam
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSixJni_getpwnam
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSixJni_uname
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSixJni_time
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSixJni_strftime
        (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
