/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_HelloJni */

#ifndef _Included_com_crab_test_apuedemo_jni_HelloJni
#define _Included_com_crab_test_apuedemo_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_HelloJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_HelloJni_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
