/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterNineJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterNineJni
#define _Included_com_crab_test_apuedemo_jni_ChapterNineJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterNineJni
 * Method:    processGroupId
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterNineJni_processGroupId
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterNineJni_orphanProcessGroup
(JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
