/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterSevenJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterSevenJni
#define _Included_com_crab_test_apuedemo_jni_ChapterSevenJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterSevenJni
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSevenJni_atexit
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSevenJni_environ
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSevenJni_alloc
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterSevenJni_rlimit
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
