/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crab_test_apuedemo_jni_ChapterEightJni */

#ifndef _Included_com_crab_test_apuedemo_jni_ChapterEightJni
#define _Included_com_crab_test_apuedemo_jni_ChapterEightJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crab_test_apuedemo_jni_ChapterEightJni
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_test
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_processId
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_fork
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_vfork
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_exit
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_waitTest
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_waitpid
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_waitid
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_wait4
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_competition
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_exec
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_nice
        (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_crab_test_apuedemo_jni_ChapterEightJni_times
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
